name: cron-fetch
on:
  push:
    branches: [main]
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '46 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: Build
        run: go build -v ./...
      - name: Fetch zip
        run: go run main.go
