name: cron-fetch
on:
  push:
    branches: [main]
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '46 * * * *'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
    - name: Check out source code
      uses: actions/checkout@v3
    - name: Run main.go
      run: | 
        go mod init github.com/iunn-sh/codex-mirror
        go build .
